create table public.beer_versions (
  id bigint generated by default as identity primary key,
  beer_id bigint not null references public.beers(id) on delete cascade,
  version_year smallint null,
  valid_from date null,
  valid_to date null,
  plato numeric null,
  abv numeric null,
  ibu numeric null,
  style_id bigint null references public.beer_styles(id) on delete set null,
  is_current boolean not null default false,
  notes text null,
  created_at timestamptz not null default now(),
  constraint beer_versions_year_check
    check (version_year is null or version_year between 1000 and 2100),
  constraint beer_versions_valid_range_check
    check (valid_from is null or valid_to is null or valid_to >= valid_from)
);

create unique index beer_versions_one_current_per_beer_idx
  on public.beer_versions(beer_id)
  where is_current;

create index beer_versions_beer_id_idx
  on public.beer_versions(beer_id);

create index beer_versions_year_idx
  on public.beer_versions(version_year);

create table public.beer_version_hops (
  beer_version_id bigint not null
    references public.beer_versions(id) on delete cascade,
  hop_id bigint not null
    references public.hops(id) on delete restrict,
  primary key (beer_version_id, hop_id)
);

create index beer_version_hops_hop_id_idx
  on public.beer_version_hops(hop_id);

alter table public.tastings
  add column beer_version_id bigint null
    references public.beer_versions(id) on delete set null;

create index tastings_beer_version_id_idx
  on public.tastings(beer_version_id);

alter table public.beer_versions enable row level security;
alter table public.beer_version_hops enable row level security;

create policy "Authenticated users can manage beer versions"
  on public.beer_versions
  for all
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can manage beer version hops"
  on public.beer_version_hops
  for all
  to authenticated
  using (true)
  with check (true);

grant select, insert, update, delete
  on public.beer_versions
  to authenticated;

grant select, insert, update, delete
  on public.beer_version_hops
  to authenticated;

grant usage, select
  on sequence public.beer_versions_id_seq
  to authenticated;

insert into public.beer_versions (
  beer_id,
  plato,
  abv,
  ibu,
  style_id,
  is_current,
  notes
)
select
  b.id,
  b.plato,
  b.abv,
  b.ibu,
  b.style_id,
  true,
  'Aktuální katalogová verze při zavedení verzování'
from public.beers b;

insert into public.beer_version_hops (
  beer_version_id,
  hop_id
)
select
  bv.id,
  bh.hop_id
from public.beer_versions bv
join public.beer_hops bh
  on bh.beer_id = bv.beer_id
where bv.is_current
on conflict do nothing;

insert into public.beer_versions (
  beer_id,
  version_year,
  plato,
  abv,
  ibu,
  style_id,
  is_current,
  notes
)
select distinct
  t.beer_id,
  extract(year from t.tasted_on)::smallint,
  t.plato,
  t.abv,
  t.ibu,
  b.style_id,
  false,
  'Historická verze odvozená z uloženého snapshotu ochutnávky'
from public.tastings t
join public.beers b
  on b.id = t.beer_id
where
  (t.plato is not null and t.plato is distinct from b.plato)
  or (t.abv is not null and t.abv is distinct from b.abv)
  or (t.ibu is not null and t.ibu is distinct from b.ibu);

insert into public.beer_version_hops (
  beer_version_id,
  hop_id
)
select
  bv.id,
  bh.hop_id
from public.beer_versions bv
join public.beer_hops bh
  on bh.beer_id = bv.beer_id
where not bv.is_current
on conflict do nothing;

update public.tastings t
set beer_version_id = bv.id
from public.beer_versions bv
where bv.beer_id = t.beer_id
  and not bv.is_current
  and bv.version_year = extract(year from t.tasted_on)::smallint
  and bv.plato is not distinct from t.plato
  and bv.abv is not distinct from t.abv
  and bv.ibu is not distinct from t.ibu;

update public.tastings t
set beer_version_id = bv.id
from public.beer_versions bv
where bv.beer_id = t.beer_id
  and bv.is_current
  and t.beer_version_id is null;
