-- Canonical BeerApp model: brewery -> brand -> beer -> beer version -> tasting.
-- Production clean-reset/archive was performed separately on 2026-09-15.

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null,
  country text,
  website text,
  notes text,
  created_at timestamptz not null default now()
);

comment on table public.brands is
  'Product brands. Ownership groups are intentionally out of scope; brand is the middle level brewery -> brand -> beer.';

create index if not exists brands_name_lower_idx
  on public.brands (lower(name));

alter table public.brands enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'brands'
      and policyname = 'Authenticated users can manage brands'
  ) then
    create policy "Authenticated users can manage brands"
      on public.brands for all to authenticated
      using (true) with check (true);
  end if;
end $$;

grant select, insert, update, delete on public.brands to authenticated;
grant usage, select on sequence public.brands_id_seq to authenticated;

alter table public.beers
  add column if not exists brand_id bigint references public.brands(id) on delete restrict;

comment on column public.beers.brand_id is
  'Canonical product brand. One beer belongs to exactly one brand once verified.';

create index if not exists beers_brand_id_idx on public.beers (brand_id);

alter table public.beer_versions
  add column if not exists brewery_id bigint references public.breweries(id) on delete restrict;

comment on column public.beer_versions.brewery_id is
  'Canonical producing brewery for this exact current/historical beer version. Brewery statistics must use this column.';

create index if not exists beer_versions_brewery_id_idx
  on public.beer_versions (brewery_id);

comment on column public.beers.brewery_id is
  'Compatibility cache for the current producing brewery. NOT authoritative for historical brewery statistics; use beer_versions.brewery_id.';

create or replace function private.ensure_current_beer_version()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if not exists (
    select 1 from public.beer_versions
    where beer_id = new.id and is_current
  ) then
    insert into public.beer_versions (
      beer_id, brewery_id, plato, abv, ibu, style_id, is_current, notes
    ) values (
      new.id, new.brewery_id, new.plato, new.abv, new.ibu, new.style_id, true,
      'Aktuální katalogová verze'
    );
  end if;
  return new;
end;
$function$;

create or replace function private.sync_current_beer_version()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_current_id bigint;
begin
  if old.brewery_id is not distinct from new.brewery_id
     and old.style_id is not distinct from new.style_id
     and old.plato is not distinct from new.plato
     and old.abv is not distinct from new.abv
     and old.ibu is not distinct from new.ibu then
    return new;
  end if;

  v_current_id := private.freeze_current_beer_version(new.id);

  if v_current_id is null then
    insert into public.beer_versions (
      beer_id, brewery_id, plato, abv, ibu, style_id, is_current, notes
    ) values (
      new.id, new.brewery_id, new.plato, new.abv, new.ibu, new.style_id, true,
      'Aktuální katalogová verze'
    );
  else
    update public.beer_versions
    set brewery_id = new.brewery_id,
        plato = new.plato,
        abv = new.abv,
        ibu = new.ibu,
        style_id = new.style_id,
        version_year = null,
        valid_from = null,
        valid_to = null,
        notes = 'Aktuální katalogová verze'
    where id = v_current_id;
  end if;

  return new;
end;
$function$;
