-- Catalog identity and reviewed beer versions.
-- A beer is identified by the immutable brewery + brand + beer name tuple.

alter table public.beers
  add column if not exists is_catalog boolean not null default false,
  add column if not exists catalog_confirmed_at timestamptz,
  add column if not exists catalog_confirmed_by uuid references auth.users(id) on delete set null,
  add column if not exists created_by uuid references auth.users(id) on delete set null;

comment on column public.beers.is_catalog is
  'True after the catalog administrator has reviewed and confirmed this beer as an autocomplete reference.';

create unique index if not exists beers_identity_unique_idx
  on public.beers (brewery_id, brand_id, lower(trim(name)))
  where brand_id is not null;

create or replace function private.guard_catalog_beer_update()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_user_id uuid := auth.uid();
  v_admin_id constant uuid := '17be5dc3-a3f9-4fd2-ae90-dee7692034fc';
begin
  if current_setting('beerapp.version_rpc', true) = 'on' or v_user_id = v_admin_id then
    return new;
  end if;

  if old.brewery_id is distinct from new.brewery_id
     or old.brand_id is distinct from new.brand_id
     or old.name is distinct from new.name then
    raise exception 'Pivovar, značka a název tvoří pevnou identitu piva.';
  end if;

  if v_user_id is null or not exists (
    select 1 from public.tastings
    where beer_id = old.id
      and user_id = v_user_id
      and tasted_on >= date '2026-09-01'
  ) then
    raise exception 'Upravit lze jen vlastní pivo ochutnané od 1. 9. 2026.';
  end if;

  if new.style_id is null or new.plato is null or new.abv is null then
    raise exception 'Pro novou verzi je povinný styl, stupňovitost a obsah alkoholu.';
  end if;

  return new;
end;
$function$;

drop trigger if exists beers_guard_catalog_update on public.beers;
create trigger beers_guard_catalog_update
before update on public.beers
for each row execute function private.guard_catalog_beer_update();

revoke all on function private.guard_catalog_beer_update() from public, anon, authenticated;

alter table public.beer_versions
  add column if not exists ebc numeric,
  add column if not exists photo_url text,
  add column if not exists is_non_alcoholic boolean not null default false,
  add column if not exists created_by uuid references auth.users(id) on delete set null,
  add column if not exists supersedes_version_id bigint references public.beer_versions(id) on delete set null;

update public.beer_versions bv
set ebc = b.ebc,
    photo_url = b.photo_url,
    is_non_alcoholic = coalesce(b.is_non_alcoholic, false)
from public.beers b
where b.id = bv.beer_id
  and bv.is_current;

create table if not exists public.brewery_brands (
  brewery_id bigint not null references public.breweries(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (brewery_id, brand_id)
);

insert into public.brewery_brands (brewery_id, brand_id)
select distinct brewery_id, brand_id
from public.beers
where brand_id is not null
on conflict do nothing;

alter table public.brewery_brands enable row level security;

drop policy if exists "Authenticated users can read brewery brands" on public.brewery_brands;
create policy "Authenticated users can read brewery brands"
  on public.brewery_brands for select to authenticated using (true);

drop policy if exists "Authenticated users can create brewery brands" on public.brewery_brands;
create policy "Authenticated users can create brewery brands"
  on public.brewery_brands for insert to authenticated
  with check (created_by is null or created_by = auth.uid());

drop policy if exists "Authenticated users can remove brewery brands" on public.brewery_brands;
create policy "Authenticated users can remove brewery brands"
  on public.brewery_brands for delete to authenticated using (true);

grant select, insert, delete on public.brewery_brands to authenticated;

create table if not exists public.catalog_events (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references auth.users(id) on delete cascade,
  beer_id bigint not null references public.beers(id) on delete cascade,
  brewery_id bigint not null references public.breweries(id) on delete cascade,
  event_type text not null check (event_type in ('beer_created', 'beer_confirmed', 'beer_version_created')),
  show_in_timeline boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists catalog_events_created_at_idx
  on public.catalog_events (created_at desc);

alter table public.catalog_events enable row level security;

drop policy if exists "Authenticated users can read catalog events" on public.catalog_events;
create policy "Authenticated users can read catalog events"
  on public.catalog_events for select to authenticated using (true);

drop policy if exists "Authenticated users can create own catalog events" on public.catalog_events;
create policy "Authenticated users can create own catalog events"
  on public.catalog_events for insert to authenticated
  with check (actor_user_id = auth.uid());

grant select, insert on public.catalog_events to authenticated;
grant usage, select on sequence public.catalog_events_id_seq to authenticated;

create or replace function private.ensure_current_beer_version()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if not exists (
    select 1 from public.beer_versions
    where beer_id = new.id and is_current
  ) then
    insert into public.beer_versions (
      beer_id, brewery_id, plato, abv, ibu, ebc, style_id,
      photo_url, is_non_alcoholic, is_current, notes, created_by
    ) values (
      new.id, new.brewery_id, new.plato, new.abv, new.ibu, new.ebc, new.style_id,
      new.photo_url, coalesce(new.is_non_alcoholic, false), true, new.notes, new.created_by
    );
  end if;
  return new;
end;
$function$;

create or replace function private.sync_current_beer_version()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_current_id bigint;
begin
  if current_setting('beerapp.version_rpc', true) = 'on' then
    return new;
  end if;

  if old.brewery_id is not distinct from new.brewery_id
     and old.style_id is not distinct from new.style_id
     and old.plato is not distinct from new.plato
     and old.abv is not distinct from new.abv
     and old.ibu is not distinct from new.ibu
     and old.ebc is not distinct from new.ebc
     and old.photo_url is not distinct from new.photo_url
     and old.notes is not distinct from new.notes
     and old.is_non_alcoholic is not distinct from new.is_non_alcoholic then
    return new;
  end if;

  v_current_id := private.freeze_current_beer_version(new.id);

  if v_current_id is null then
    insert into public.beer_versions (
      beer_id, brewery_id, plato, abv, ibu, ebc, style_id,
      photo_url, is_non_alcoholic, is_current, notes
    ) values (
      new.id, new.brewery_id, new.plato, new.abv, new.ibu, new.ebc, new.style_id,
      new.photo_url, coalesce(new.is_non_alcoholic, false), true, new.notes
    );
  else
    update public.beer_versions
    set brewery_id = new.brewery_id,
        plato = new.plato,
        abv = new.abv,
        ibu = new.ibu,
        ebc = new.ebc,
        style_id = new.style_id,
        photo_url = new.photo_url,
        is_non_alcoholic = coalesce(new.is_non_alcoholic, false),
        version_year = null,
        valid_from = null,
        valid_to = null,
        notes = new.notes
    where id = v_current_id;
  end if;

  return new;
end;
$function$;

drop trigger if exists beers_sync_current_version on public.beers;
create trigger beers_sync_current_version
after update of brewery_id, style_id, plato, abv, ibu, ebc, photo_url, notes, is_non_alcoholic
on public.beers
for each row execute function private.sync_current_beer_version();

create or replace function private.sync_current_version_hop_insert()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_current_id bigint;
begin
  if current_setting('beerapp.version_rpc', true) = 'on' then
    return new;
  end if;
  v_current_id := private.freeze_current_beer_version(new.beer_id);
  if v_current_id is not null then
    insert into public.beer_version_hops (beer_version_id, hop_id)
    values (v_current_id, new.hop_id) on conflict do nothing;
  end if;
  return new;
end;
$function$;

create or replace function private.sync_current_version_hop_delete()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_current_id bigint;
begin
  if current_setting('beerapp.version_rpc', true) = 'on' then
    return old;
  end if;
  v_current_id := private.freeze_current_beer_version(old.beer_id);
  if v_current_id is not null then
    delete from public.beer_version_hops
    where beer_version_id = v_current_id and hop_id = old.hop_id;
  end if;
  return old;
end;
$function$;

create or replace function public.update_catalog_beer_version(
  p_beer_id bigint,
  p_style_id bigint,
  p_plato numeric,
  p_abv numeric,
  p_ibu numeric default null,
  p_ebc numeric default null,
  p_notes text default null,
  p_photo_url text default null,
  p_is_non_alcoholic boolean default false,
  p_hop_ids bigint[] default '{}'::bigint[],
  p_collaborator_ids bigint[] default '{}'::bigint[]
)
returns table(version_id bigint, changed boolean)
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_user_id uuid := auth.uid();
  v_admin_id constant uuid := '17be5dc3-a3f9-4fd2-ae90-dee7692034fc';
  v_beer public.beers%rowtype;
  v_current public.beer_versions%rowtype;
  v_new_version_id bigint;
  v_current_hops bigint[];
  v_current_collaborators bigint[];
  v_hops bigint[] := coalesce((select array_agg(distinct x order by x) from unnest(coalesce(p_hop_ids, '{}'::bigint[])) x), '{}'::bigint[]);
  v_collaborators bigint[] := coalesce((select array_agg(distinct x order by x) from unnest(coalesce(p_collaborator_ids, '{}'::bigint[])) x), '{}'::bigint[]);
begin
  if v_user_id is null then
    raise exception 'Uživatel není přihlášen.';
  end if;

  select * into v_beer from public.beers where id = p_beer_id for update;
  if not found then raise exception 'Pivo nebylo nalezeno.'; end if;

  if v_user_id <> v_admin_id and not exists (
    select 1 from public.tastings
    where beer_id = p_beer_id
      and user_id = v_user_id
      and tasted_on >= date '2026-09-01'
  ) then
    raise exception 'Upravit lze jen vlastní pivo ochutnané od 1. 9. 2026.';
  end if;

  if p_style_id is null or p_plato is null or p_abv is null then
    raise exception 'Pro novou verzi je povinný styl, stupňovitost a obsah alkoholu.';
  end if;

  select * into v_current
  from public.beer_versions
  where beer_id = p_beer_id and is_current
  for update;

  if not found then raise exception 'Pivo nemá aktuální katalogovou verzi.'; end if;

  select coalesce(array_agg(hop_id order by hop_id), '{}'::bigint[])
    into v_current_hops
  from public.beer_version_hops where beer_version_id = v_current.id;

  select coalesce(array_agg(brewery_id order by brewery_id), '{}'::bigint[])
    into v_current_collaborators
  from public.beer_version_collaborators where beer_version_id = v_current.id;

  if v_current.style_id is not distinct from p_style_id
     and v_current.plato is not distinct from p_plato
     and v_current.abv is not distinct from p_abv
     and v_current.ibu is not distinct from p_ibu
     and v_current.ebc is not distinct from p_ebc
     and v_current.notes is not distinct from nullif(trim(p_notes), '')
     and v_current.photo_url is not distinct from nullif(trim(p_photo_url), '')
     and v_current.is_non_alcoholic is not distinct from coalesce(p_is_non_alcoholic, false)
     and v_current_hops = v_hops
     and v_current_collaborators = v_collaborators then
    return query select v_current.id, false;
    return;
  end if;

  perform set_config('beerapp.version_rpc', 'on', true);

  update public.beer_versions
  set is_current = false,
      valid_to = current_date,
      version_year = coalesce(version_year, extract(year from current_date)::smallint)
  where id = v_current.id;

  insert into public.beer_versions (
    beer_id, brewery_id, version_year, valid_from, plato, abv, ibu, ebc,
    style_id, is_current, notes, photo_url, is_non_alcoholic, created_by,
    supersedes_version_id
  ) values (
    v_beer.id, v_beer.brewery_id, extract(year from current_date)::smallint,
    current_date, p_plato, p_abv, p_ibu, p_ebc, p_style_id, true,
    nullif(trim(p_notes), ''), nullif(trim(p_photo_url), ''),
    coalesce(p_is_non_alcoholic, false), v_user_id, v_current.id
  ) returning id into v_new_version_id;

  insert into public.beer_version_hops (beer_version_id, hop_id)
  select v_new_version_id, x from unnest(v_hops) x;

  insert into public.beer_version_collaborators (beer_version_id, brewery_id, display_order)
  select v_new_version_id, x, ordinality::integer
  from unnest(v_collaborators) with ordinality as t(x, ordinality);

  update public.beers
  set style_id = p_style_id,
      plato = p_plato,
      abv = p_abv,
      ibu = p_ibu,
      ebc = p_ebc,
      notes = nullif(trim(p_notes), ''),
      photo_url = nullif(trim(p_photo_url), ''),
      is_non_alcoholic = coalesce(p_is_non_alcoholic, false)
  where id = v_beer.id;

  delete from public.beer_hops where beer_id = v_beer.id;
  insert into public.beer_hops (beer_id, hop_id)
  select v_beer.id, x from unnest(v_hops) x;

  insert into public.catalog_events (actor_user_id, beer_id, brewery_id, event_type)
  values (v_user_id, v_beer.id, v_beer.brewery_id, 'beer_version_created');

  return query select v_new_version_id, true;
end;
$function$;

create or replace function public.confirm_catalog_beer(p_beer_id bigint)
returns boolean
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_user_id uuid := auth.uid();
  v_admin_id constant uuid := '17be5dc3-a3f9-4fd2-ae90-dee7692034fc';
  v_beer public.beers%rowtype;
  v_current public.beer_versions%rowtype;
begin
  if v_user_id is null or v_user_id <> v_admin_id then
    raise exception 'Katalogové pivo může potvrdit pouze správce katalogu.';
  end if;

  select * into v_beer from public.beers where id = p_beer_id for update;
  if not found then raise exception 'Pivo nebylo nalezeno.'; end if;
  if v_beer.brand_id is null or nullif(trim(v_beer.name), '') is null then
    raise exception 'Pivo musí mít pivovar, značku a název.';
  end if;

  select * into v_current from public.beer_versions
  where beer_id = p_beer_id and is_current;
  if not found or v_current.style_id is null or v_current.plato is null or v_current.abv is null then
    raise exception 'Před potvrzením doplň styl, stupňovitost a obsah alkoholu.';
  end if;

  if v_beer.is_catalog then return false; end if;

  update public.beers
  set is_catalog = true,
      catalog_confirmed_at = now(),
      catalog_confirmed_by = v_user_id
  where id = p_beer_id;

  insert into public.catalog_events (actor_user_id, beer_id, brewery_id, event_type)
  values (v_user_id, v_beer.id, v_beer.brewery_id, 'beer_confirmed');

  return true;
end;
$function$;

revoke all on function public.update_catalog_beer_version(bigint, bigint, numeric, numeric, numeric, numeric, text, text, boolean, bigint[], bigint[]) from public, anon;
grant execute on function public.update_catalog_beer_version(bigint, bigint, numeric, numeric, numeric, numeric, text, text, boolean, bigint[], bigint[]) to authenticated;

revoke all on function public.confirm_catalog_beer(bigint) from public, anon;
grant execute on function public.confirm_catalog_beer(bigint) to authenticated;
