-- Introduce a moderated pub/festival catalog without touching existing tasting.place text.
CREATE TABLE public.places (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (char_length(btrim(name)) BETWEEN 2 AND 160),
  city text NOT NULL DEFAULT '' CHECK (char_length(city) <= 120),
  country text NOT NULL DEFAULT '' CHECK (char_length(country) <= 120),
  category text NOT NULL CHECK (category IN ('pub','festival')),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  approved boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.places ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated can view public places"
  ON public.places FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated can suggest new places"
  ON public.places FOR INSERT TO authenticated
  WITH CHECK (created_by = (select auth.uid()) AND approved = false);
CREATE POLICY "Catalog admin can maintain places"
  ON public.places FOR UPDATE TO authenticated
  USING ((select auth.uid()) = '17be5dc3-a3f9-4fd2-ae90-dee7692034fc'::uuid)
  WITH CHECK ((select auth.uid()) = '17be5dc3-a3f9-4fd2-ae90-dee7692034fc'::uuid);
GRANT SELECT, INSERT, UPDATE ON public.places TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.places_id_seq TO authenticated;
CREATE INDEX places_suggest_name_idx ON public.places (lower(name));
CREATE INDEX places_recent_created_idx ON public.places (created_at DESC);
ALTER TABLE public.tastings ADD COLUMN place_id bigint REFERENCES public.places(id) ON DELETE RESTRICT;
ALTER TABLE public.tastings ADD COLUMN place_category text
  CONSTRAINT tastings_place_category_check CHECK (place_category IS NULL OR place_category IN ('home','pub','festival'));
CREATE INDEX tastings_place_id_idx ON public.tastings (place_id) WHERE place_id IS NOT NULL;
COMMENT ON COLUMN public.tastings.place IS 'Legacy place text snapshot; never overwrite old rows during catalog rollout.';
COMMENT ON COLUMN public.tastings.place_id IS 'Optional link to a public pub/festival catalog place; NULL for home and legacy text.';
COMMENT ON COLUMN public.tastings.place_category IS 'Optional category; home does not create a public catalog location.';
